### PR TITLE
Generalize console control

### LINKED ISSUE #297: Kubernetes config with 'exec' resource where exec requires MFA hangs
A common way to configure AWS EKS in kube config is
```
user:
  exec:
    apiVersion: client.authentication.k8s.io/v1alpha1
    command: aws-iam-authenticator
    args: [token, -i, infracore-test-1, --cache]
    env:
    - name: AWS_PROFILE
      value: <profile>
```

This will cache and re-use an MFA token if using an account with MFA, but if the token needs to be re-requested Wash hangs, then eventually times out and crashes the terminal.

We need to identify and expose that request for an MFA token when it happens.

----

For completeness, the way the AWS CLI tool sets up kube config is with
```
user:
  exec:
    apiVersion: client.authentication.k8s.io/v1alpha1
    command: aws
    args: [eks get-token --cluster-name <cluster>]
    env:
    - name: AWS_PROFILE
      value: <profile>
```
which doesn't cache the token at all, so it attempts to request an MFA token every time you run kubectl.

### PR DESCRIPTION
**Pull request by MikaelSmith**
Sometimes a plugin needs control of the console for a prompt it doesn't make directly. Get control before calling all primitives that take a context (as a proxy for potential network activity or execs).

This isn't entirely safe. If it's backgrounded and prompts for input it may not exit cleanly. Using `plugin.Prompt` guards against this issue.

Fixes #297.

Signed-off-by: Michael Smith <michael.smith@puppet.com>

### CODE REVIEW

**Comment by ekinanp** [comment]
So this handles the case when the plugin's API prompts for something, right?

File: plugin/interactive.go [hunk 1]
```diff
@@ -56,27 +63,39 @@ func Prompt(msg string) (string, error) {
...
 	curGrp := unix.Getpgrp()
 
-	var v string
-	if inGrp == curGrp {
-		// We control stdin
-		fmt.Fprintf(os.Stderr, "%s: ", msg)
-		_, err = fmt.Scanln(&v)
-	} else {
-		// Need to get control, prompt, then return control.
+	if inGrp != curGrp {
```
Comment (MikaelSmith) [inline plugin/interactive.go]: The problem might be that Ctrl-C is terminating the daemon when it has stdin. So I'm going to try catching SIGTERM and telling it to stop the context (meaning fn needs to be more opinionated about its signature).

**Comment by MikaelSmith** [comment]
Yes.

**Comment by MikaelSmith** [comment]
Ok, I think this works better now.

File: plugin/interactive.go [hunk 2]
```diff
@@ -56,27 +55,51 @@ func Prompt(msg string) (string, error) {
...
 	if inGrp == curGrp {
-		// We control stdin
+		return fn(ctx)
+	}
+
+	sigCh := make(chan os.Signal, 1)
+	signal.Notify(sigCh, syscall.SIGINT)
+	cancelCtx, cancel := context.WithCancel(ctx)
+	go func() {
+		<-sigCh
```
Comment (ekinanp) [inline plugin/interactive.go]: This won't block forever, will it? Guessing the `Reset` below prevents that?

File: plugin/methodWrappers.go [hunk 3]
```diff
@@ -198,8 +210,10 @@ func Signal(ctx context.Context, s Signalable, signal string) error {
 	}
 
 	// Go ahead and send the signal
-	err = s.Signal(ctx, signal)
-	if err != nil {
+	if err = withConsole(ctx, func(c context.Context) (err error) {
```
Comment (ekinanp) [inline plugin/methodWrappers.go]: Nit: `err =` part on separate line

File: plugin/methodWrappers.go [hunk 4]
```diff
@@ -218,8 +232,10 @@ func Signal(ctx context.Context, s Signalable, signal string) error {
 
 // Delete deletes the given entry.
 func Delete(ctx context.Context, d Deletable) (deleted bool, err error) {
-	deleted, err = d.Delete(ctx)
-	if err != nil {
+	if err = withConsole(ctx, func(c context.Context) (err error) {
```
Comment (ekinanp) [inline plugin/methodWrappers.go]: Nit: `err =` part on separate line

**Review by ekinanp — COMMENTED** [review]
Most comments are about moving `err :=` stuff to a separate line. I think only one asks a legitimate question. Otherwise, this LGTM.

File: plugin/methodWrappers.go (hunk 4 above)
Comment (MikaelSmith) [reply plugin/methodWrappers.go]: You and I just disagree on this.

File: plugin/interactive.go (hunk 2 above)
Comment (MikaelSmith) [reply plugin/interactive.go]: Hmm, it might. I can probably do something about that.

Comment (MikaelSmith) [reply plugin/interactive.go]: Should be addressed now.

Comment (ekinanp) [reply plugin/interactive.go]: Why not just close `sigCh` in a defer? You'll still need to call the cancel func either way

Comment (MikaelSmith) [reply plugin/interactive.go]: Oh, didn't think of it.

**Review by ekinanp — APPROVED** [review]
