### PR TITLE
Generalize goyaml.Marshaler + some winfo improvements/fixes

### LINKED ISSUE #483: The textBuilder does not handle objects that aren't maps, arrays or primitive values
If I pass in an arbitrary type to [textBuilder](https://github.com/puppetlabs/wash/blob/master/cmd/util/marshal.go#L79-L117) that isn't an object, array, or primitive value, then https://github.com/puppetlabs/wash/blob/master/cmd/util/marshal.go#L115 gets printed, which isn't what I want. This issue's the reason why `winfo --output text` doesn't work as intended.

### PR DESCRIPTION
**Pull request by ekinanp**
Relevant `winfo` issues are #662 and #661. Generalizing goyaml.Marshaler fixes #483

### CODE REVIEW

File: cmd/info.go [hunk 1]
```diff
@@ -58,7 +60,6 @@ func infoMain(cmd *cobra.Command, args []string) exitCode {
 			}
 
 			entryMap := orderedMap{linkedhashmap.New()}
-			entryMap.Put("Path", entry.Path)
```
Comment (MikaelSmith) [inline cmd/info.go]: We can have multiple entries. Path seems like it could still be useful when we printing more than one entry.

**Review by MikaelSmith — CHANGES_REQUESTED** [review]

File: cmd/info.go (hunk 1 above)
Comment (ekinanp) [reply cmd/info.go]: The output will be a hash of `<path> => <info>`.

**Review by MikaelSmith — APPROVED** [review]
