### PR TITLE
Retry unmount if it failed due to an open file handle

### LINKED ISSUE #654: Wash requires manual intervention even after closing open file
When exiting Wash with a file opened in an editor, I encounter
```
WARN FUSE: Shutdown failed: unmount /Users/michaelsmith/Library/Caches/wash/mnt962968583: resource busy
WARN FUSE: Manual cleanup required: umount /Users/michaelsmith/Library/Caches/wash/mnt962968583
```

Even after I close the open file, it just waits for me to unmount. It shouldn't require explicitly running `umount`.

### PR DESCRIPTION
**Pull request by MikaelSmith**
Rather than wait for the user to run `umount`, retry unmounting  in case the file handle is released.

Fixes #654.

Signed-off-by: Michael Smith <michael.smith@puppet.com>

### CODE REVIEW

File: fuse/core.go [hunk 1]
```diff
@@ -244,8 +244,14 @@ func ServeFuseFS(
 
 			log.Infof("FUSE: Unmounting %v", mountpoint)
 			if err = fuse.Unmount(mountpoint); err != nil {
-				log.Warnf("FUSE: Shutdown failed: %v", err.Error())
+				log.Warnf("FUSE: Shutdown failed: %v", err)
 				log.Warnf("FUSE: Manual cleanup required: umount %v", mountpoint)
+
+				// Retry in a loop until no longer blocked buy an open handle.
+				// All errors are `*os.PathError`, so we just match a known error string.
+				for ; err != nil && err.Error() == "resource busy"; err = fuse.Unmount(mountpoint) {
```
Comment (ekinanp) [inline fuse/core.go]: Is "resource busy" platform agnostic? Also, what are the chances that this could be an infinite loop (i.e. should there be a counter)?

**Review by ekinanp — APPROVED** [review]
LGTM, just a comment.

File: fuse/core.go (hunk 1 above)
Comment (MikaelSmith) [reply fuse/core.go]: I'm not sure about platform agnostic, I'll try it out on a linux machine.

I'm pretty sure it's not an infinite loop. Once the fs is unmounted, the error message changes to `invalid argument`.

Comment (MikaelSmith) [reply fuse/core.go]: Ah, it's `Resource busy` on Linux :)

Comment (MikaelSmith) [reply fuse/core.go]: Updated so it now works on Linux and macOS.

Comment (ekinanp) [reply fuse/core.go]: Re: infinite loop, I'm mostly worried about those open handles never closing so resource busy is always returned. Sounds like that's not an issue?

Comment (MikaelSmith) [reply fuse/core.go]: Well, the current behavior is it doesn't exit in that case either.

Comment (ekinanp) [reply fuse/core.go]: Maybe a warning could be useful? Least let the user know that something went wrong with the unmount?

**Review by ekinanp — APPROVED** [review]

File: fuse/core.go (hunk 1 above)
Comment (MikaelSmith) [reply fuse/core.go]: That's what happens 2 lines up.
